#!/bin/sh

case "$1" in
    start)
        echo "Loading ldd modules"
        modprobe hello
        modprobe faulty
        modprobe scull
	rm -f /dev/faulty /dev/scull0 /dev/scull1 /dev/scull2 /dev/scull3
	mknod /dev/faulty c 248 0
	mknod /dev/scull0 c 247 0
	mknod /dev/scull1 c 247 1
	mknod /dev/scull2 c 247 2
	mknod /dev/scull3 c 247 3
        ;;
    stop)
        echo "Unloading ldd modules"
        rmmod scull
        rmmod faulty
        rmmod hello
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
